const shows = [
  {
    id: "amphibia",
    title: "Amphibia",
    level: "A2",
    type: "animation",
    typeLabel: "Animation",
    watch: "dub",
    watchLabel: "English dub",
    difficulty: "easy",
    icon: "🐸",
    colors: ["#22c55e", "#0891b2"],
    description: "Clear dialogue and everyday vocabulary. Great for beginners.",
    note: "Try the English dub with English subtitles."
  },
  {
    id: "digimon-beatbreak",
    title: "Digimon Beatbreak",
    level: "A2",
    type: "anime",
    typeLabel: "Anime",
    watch: "dub",
    watchLabel: "English dub",
    difficulty: "easy",
    icon: "⚡",
    colors: ["#2563eb", "#7c3aed"],
    description: "A beginner-friendly anime with fairly clear dialogue.",
    note: "The English dub is easier than English subtitles."
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer",
    level: "A2",
    type: "anime",
    typeLabel: "Anime",
    watch: "dub",
    watchLabel: "English dub",
    difficulty: "easy",
    icon: "⚔️",
    colors: ["#ef4444", "#7c3aed"],
    description: "Understandable English dub with fantasy and combat vocabulary.",
    note: "Start with the English dub."
  },
  {
    id: "dota",
    title: "Dota: Dragon’s Blood",
    level: "B1",
    type: "animation",
    typeLabel: "Animation",
    watch: "original",
    watchLabel: "Original English",
    difficulty: "easy",
    icon: "🐉",
    colors: ["#dc2626", "#1e293b"],
    description: "Original English with fantasy, magic and battle vocabulary.",
    note: "English subtitles are recommended at B1."
  },
  {
    id: "wolverine",
    title: "The Wolverine",
    year: "2013",
    level: "B1",
    type: "movie",
    typeLabel: "Movie",
    watch: "original",
    watchLabel: "Original English",
    difficulty: "easy",
    icon: "🐺",
    colors: ["#f59e0b", "#475569"],
    description: "An action movie with fairly clear and standard dialogue.",
    note: "A good bridge from A2 to B1."
  },
  {
    id: "forever-my-girl",
    title: "Forever My Girl",
    year: "2018",
    level: "B1",
    type: "movie",
    typeLabel: "Movie",
    watch: "original",
    watchLabel: "Original English",
    difficulty: "easy",
    icon: "🎸",
    colors: ["#ec4899", "#f97316"],
    description: "Everyday and emotional conversations with an American accent.",
    note: "Useful for natural conversational English."
  },
  {
    id: "electric-state",
    title: "The Electric State",
    year: "2025",
    level: "B1",
    type: "movie",
    typeLabel: "Movie",
    watch: "original",
    watchLabel: "Original English",
    difficulty: "easy",
    icon: "🤖",
    colors: ["#0ea5e9", "#6366f1"],
    description: "Standard English dialogue with some science-fiction vocabulary.",
    note: "A manageable B1 science-fiction movie."
  },
  {
    id: "jurassic-world",
    title: "Jurassic World Rebirth",
    year: "2025",
    level: "B1",
    type: "movie",
    typeLabel: "Movie",
    watch: "original",
    watchLabel: "Original English",
    difficulty: "easy",
    icon: "🦖",
    colors: ["#15803d", "#92400e"],
    description: "Adventure dialogue with some scientific vocabulary.",
    note: "English subtitles are useful at B1."
  },
  {
    id: "insidious-key",
    title: "Insidious: The Last Key",
    year: "2018",
    level: "B1",
    type: "movie",
    typeLabel: "Movie",
    watch: "original",
    watchLabel: "Original English",
    difficulty: "easy",
    icon: "🔑",
    colors: ["#334155", "#7f1d1d"],
    description: "Mostly general English with a horror atmosphere.",
    note: "A good starter horror movie."
  },
  {
    id: "chained-soldier",
    title: "Chained Soldier",
    level: "B1",
    type: "anime",
    typeLabel: "Anime",
    watch: "sub",
    watchLabel: "English subtitles",
    difficulty: "medium",
    icon: "⛓️",
    colors: ["#7c3aed", "#be123c"],
    description: "Not extremely complex, but some scenes are fast.",
    note: "Use English subtitles."
  },
  {
    id: "clevatess",
    title: "Clevatess",
    level: "B1",
    type: "anime",
    typeLabel: "Anime",
    watch: "dub",
    watchLabel: "English dub",
    difficulty: "medium",
    icon: "👹",
    colors: ["#9333ea", "#0f172a"],
    description: "A monster becomes human and enters the human world.",
    note: "The English dub is the easier op
